# Generated by Django 4.1 on 2022-08-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_intenciones_context_intenciones_patterns_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intenciones',
            new_name='Intent',
        ),
    ]
